# Generated by Django 5.2.11 on 2026-08-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('hex_code', models.CharField(help_text='e.g. #1B3A5C — used for the swatch dot in the app', max_length=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='bikes.bike')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BikeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='bikes/360/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bikes.bikecolorvariant')),
            ],
            options={
                'ordering': ['frame_number'],
                'unique_together': {('variant', 'frame_number')},
            },
        ),
    ]
