# Generated by Django 5.2.11 on 2026-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_bikecolorvariant_bikeframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikecolorvariant',
            name='hex_code',
        ),
        migrations.AddField(
            model_name='bikecolorvariant',
            name='tank_image',
            field=models.ImageField(blank=True, null=True, upload_to='bike_tanks/'),
        ),
    ]
