# Generated by Django 5.2.11 on 2026-08-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('ride_report', 'Ride Report'), ('heritage', 'Heritage'), ('gear_guide', 'Gear Guide')], max_length=20)),
                ('excerpt', models.CharField(help_text='Short teaser shown on the journal list', max_length=280)),
                ('content', models.TextField(help_text='Full article body. Separate paragraphs with a blank line.')),
                ('cover_image', models.ImageField(upload_to='journal/covers/')),
                ('author_name', models.CharField(default='Royal Enfield', max_length=100)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=4)),
                ('published_at', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
