# Generated by Django 5.2.11 on 2026-08-05 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bike Category',
                'verbose_name_plural': 'Bike Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hero_image', models.ImageField(upload_to='bikes/hero/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bikecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BikeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(help_text='HEX Color', max_length=7)),
                ('image', models.ImageField(upload_to='bikes/colors/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='bikes.bike')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('bike', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BikeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='bikes/features/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bikes.bike')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BikeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_order', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='bikes/viewer360/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='bikes.bikecolor')),
            ],
            options={
                'ordering': ['frame_order'],
            },
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bikes/gallery/')),
                ('image_type', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear'), ('left', 'Left'), ('right', 'Right'), ('top', 'Top'), ('gallery', 'Gallery')], default='gallery', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bikes.bike')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='BikeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100)),
                ('displacement', models.CharField(max_length=50)),
                ('max_power', models.CharField(max_length=50)),
                ('max_torque', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_capacity', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('kerb_weight', models.CharField(max_length=50)),
                ('seat_height', models.CharField(max_length=50)),
                ('ground_clearance', models.CharField(max_length=50)),
                ('wheelbase', models.CharField(max_length=50)),
                ('braking', models.CharField(max_length=100)),
                ('tyre_front', models.CharField(max_length=100)),
                ('tyre_rear', models.CharField(max_length=100)),
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='bikes.bike')),
            ],
        ),
    ]
